version: "3.8"
services:
  client-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    env_file:
      - .env.local
    ports:
      - "3000:3000"
  # client-prod:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.prod
  #   env_file:
  #     - .env
  #   ports:
  #     - "80:80"